server: 
  port: 8888
eureka: 
  instance: 
    instanceId:  ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring: 
  application: 
    name: configserver
  profiles: 
    active: native
  devtools: 
    add-properties: true
  cloud:
    config:
      server:
        health: 
          enabled: true
        native: 
          searchLocations: file:/config-repo