server: 
  port: 8081
  
logging: 
  group:
    sql: org.springframework.jdbc.core, org.hibernate.SQL
  level:  
    root: info
    org.springframework.web: info
    org.springframework.boot.autoconfigure.security: info
    org.hibernate: info
    sql: info 

spring:
  profiles: 
    active: default
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming: 
        physical-strategy: com.forexwatch.base.CustomPhysicalNamingStrategy  
  datasource:
    url: jdbc:mysql://localhost:3306/forexwatch?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 100
      min-idle: 2
      validation-query: select 1
      test-on-borrow: true
      aop-patterns: com.forexwatch.server.service.*
      filters: stat,log4j2
      stat: 
        mergeSql: true
        slowSqlMillis: 1500
        logSlowSql: true
      web-stat-filter: 
        enabled: true
        url-pattern: /*
        profile-enable: true
      stat-view-servlet: 
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        allow: localhost,127.0.0.1,192.168.1.1/24
        login-username: root
        login-password: 123456
  servlet: 
    multipart: 
      max-file-size: 5MB
  mvc: 
    servlet: 
      path: /
    contentnegotiation: 
      favor-path-extension: true
    pathmatch: 
      use-suffix-pattern: true
  jackson: 
    serialization: 
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    
file: 
  upload: 
    dir: ./upload/
